### ISSUE TITLE
Compatibility check

### ISSUE THREAD

**Issue by tenox7** [tenox7/wrp#4]
Verify WRP works on latest OSX and Linux

**Comment by claunia** [comment]
Mac OS X El Capitán doesn't allow loading of non-SSL URLs, Python gives an exception an exits.

**Comment by tenox7** [comment]
whats the exception

**Comment by claunia** [comment]
Latest Linux releases tend to use python3 as default, but not all. As wrp is python2 it must be directed to use python2 and not just "python". May need to check specific distros.

**Comment by claunia** [comment]
`2017-01-10 10:03:06.475 Python[1118:25855] App Transport Security has clocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
 ... something went wrong 2: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.`

IMHO, we should try to add WRP->SERVER HTTPS.

**Comment by tenox7** [comment]
no because MSIE 1.5 and Mosaic 1.0 do not have HTTPS

**Comment by tenox7** [comment]
make correct info.plist

**Comment by tenox7** [comment]
https://github.com/paulhammond/webkit2png/issues/90

**Comment by claunia** [comment]
I know they don't have https, that's why I'm saying WRP to server connection as https, while client to wrp stays as http.
E.g.: Mosaic ---HTTP--> WRP ---HTTPS---> https://example.com

That future-proofs as a lot of servers will stop using non HTTPS soon.

**Comment by tenox7** [comment]
wrp should support both http and https

**Comment by tenox7** [comment]
OK open a new issue for it then back port what they have fixed in webkit2png for this https://github.com/paulhammond/webkit2png/issues/90
