### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by Gapstare** [tenox7/wrp#41]
I tried wrp 3.0 beta on Raspberry Pi 3 (Raspbian Stretch) and when idle wrp uses about 10% cpu. Is there anything that can be done to lower this?

Great program by the way :)

**Comment by tenox7** [comment]
Thank you for reporting. Interesting! I will look in to that!

**Comment by tenox7** [comment]
ack I was able to reproduce it and not only on rpi, the issue is that chromecdp is continuously communicating with chrome browser in the background, I will open an upstream issue about this, as a workaround perhaps one browser instance could be spawned and closed per request... let me see what can be done

**Comment by tenox7** [comment]
I have opened an upstream issue https://github.com/chromedp/chromedp/issues/380

**Comment by tenox7** [comment]
Please test this unofficial build. It works for me. If confirmed I will make a new official build. Thanks!

http://tnx3.tenox.net/get//wrp/wrp-linux-rpi-test 
and
http://tnx3.tenox.net/get//wrp/wrp-linux-test

**Comment by Gapstare** [comment]
Hi there! :)
I've tested the new rpi version, it works great! when idle it doesn't even show up in ``top``. Top notch work.

**Comment by tenox7** [comment]
Awesome, thank you for reporting and testing! Closing the bug.
